---
title: "Long-form documentation of the **yaev** package"
author: "Yves Deville `<deville.yves@alpestat.com>`"
date: "`r Sys.Date()`"
---


## Compile a LaTeX document using Maxima via the **maxiplot** package

In order to compile a LaTeX document with maxima you need to have the
**Maxima** system installed (possibly with its sources) and the
**maxiplot** package working with your LaTeX distribution. Then use

```
pdflatex mydocument.tex
```
This create a number of auxiliary files, including a `.mac` file. Then

```
maxima -b mydocument.mac
```
and compile again
```
pdflatex mydocument.tex
```
This should provide the pdf file embeding the results computed by **Maxima**
In case of problems it may be required to clean the auxiliary files `.aux`,
`.mac` and `.mxp`. 


## Provided documents

The documentation includes 5 documents along with their LaTeX or
Sweave sources. Note that rhe documents `N_` do not have any header
and can not compiled, and that the `.tex` documents require the
**maxiplot**

	
- `yaev.pdf` explains why and how the probability distributions are
  evaluated in **yaev**.

- `GEV.pdf` provides details about the Generalized Extreme Value
  distribution `GEV`: probability functions and their derivatives.

- `GPD2.pdf` provide details about the two-parameter Genaralized
  Pareto distribution `GP2`: probability functions and their
  derivatives.
  
- `PP2PoisGP.pdf` The PP to Poisson-GP transform and its derivatives.

- `PoisGP2PP.pdf` The Poisson-GP to PP transform and its derivatives.




